type PageElementsMap = {
  "#page1": $w.Page;
  "#columnStrip2": $w.ColumnStrip;
  "#columnStrip1": $w.ColumnStrip;
  "#column2": $w.Column;
  "#column1": $w.Column;
  "#text2": $w.Text;
  "#button1": $w.Button;
  "#text1": $w.Text;
  "#text16": $w.Text;
  "#image3": $w.Image;
  "#button2": $w.Button;
  "#header1": $w.Header;
  "#container1": $w.HiddenCollapsedElement;
  "#footer1": $w.Footer;
  "#image2": $w.Image;
  "#horizontalMenu1": $w.Menu;
  "#verticalMenu1": $w.Menu;
  "#profile1": $w.IFrame;
  "#group1": $w.Box;
  "#text12": $w.Text;
  "#text14": $w.Text;
  "#text46": $w.Text;
  "#socialBar1": $w.HiddenCollapsedElement;
  "#text15": $w.Text;
  "#text48": $w.Text;
  "#image4": $w.Image;
  "#text71": $w.Text;
}