type PageElementsMap = {
  "#page1": $w.Page;
  "#text72": $w.Text;
  "#dataset1": $w.dataset;
  "#companyName": $w.TextInput;
  "#phoneNumber": $w.TextInput;
  "#email": $w.TextInput;
  "#password": $w.TextInput;
  "#submitButton": $w.Button;
  "#text73": $w.Text;
  "#text74": $w.Text;
  "#addressInput1": $w.AddressInput;
  "#header1": $w.Header;
  "#container1": $w.HiddenCollapsedElement;
  "#footer1": $w.Footer;
  "#image2": $w.Image;
  "#horizontalMenu1": $w.Menu;
  "#verticalMenu1": $w.Menu;
  "#profile1": $w.IFrame;
  "#group1": $w.Box;
  "#text12": $w.Text;
  "#text14": $w.Text;
  "#text46": $w.Text;
  "#socialBar1": $w.HiddenCollapsedElement;
  "#text15": $w.Text;
  "#text48": $w.Text;
  "#image4": $w.Image;
  "#text71": $w.Text;
}